name: Delete branch after PR merge

on:
  pull_request:
    types: [closed]

jobs:
  delete_branch:
    # Chỉ chạy khi PR đã merged
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # cần để xoá ref

    steps:
      - name: Skip if PR is from a fork
        if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
        run: |
          echo "PR đến từ fork (${{
            github.event.pull_request.head.repo.full_name
          }}), bỏ qua xoá branch."

      - name: Delete head branch (same repo)
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        run: |
          BRANCH="${{ github.event.pull_request.head.ref }}"
          echo "Deleting branch: $BRANCH"

          # Dùng git push --delete với GITHUB_TOKEN
          git init -q
          git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          # Thử xoá, nếu không tồn tại/đã xoá thì không fail
          git push origin --delete "$BRANCH" || echo "Branch not found or already deleted."
